---
name: 'build container images'

on:
  push:
    branches:
      - test535
    tags:
      - '*'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  # self-hosted-jobs:
  #   uses: ./.github/workflows/image_build.yml
  #   with:
  #     tag-latest: ${{ matrix.tag-latest }}
  #     tag-suffix: ${{ matrix.tag-suffix }}
  #     ffmpeg: ${{ matrix.ffmpeg }}
  #     image-type: ${{ matrix.image-type }}
  #     build-type: ${{ matrix.build-type }}
  #     cuda-major-version: ${{ matrix.cuda-major-version }}
  #     cuda-minor-version: ${{ matrix.cuda-minor-version }}
  #     platforms: ${{ matrix.platforms }}
  #     runs-on: ${{ matrix.runs-on }}
  #     base-image: ${{ matrix.base-image }}
  #     grpc-base-image: ${{ matrix.grpc-base-image }}
  #     aio: ${{ matrix.aio }}
  #     makeflags: ${{ matrix.makeflags }}
  #     latest-image: ${{ matrix.latest-image }}
  #     latest-image-aio: ${{ matrix.latest-image-aio }}
  #   secrets:
  #     dockerUsername: ${{ secrets.DOCKER_USER }}
  #     dockerPassword: ${{ secrets.DOCKER_TOKEN }}
  #     # quayUsername: ${{ secrets.LOCALAI_REGISTRY_USERNAME }}
  #     # quayPassword: ${{ secrets.LOCALAI_REGISTRY_PASSWORD }}
  #   strategy:
  #     # Pushing with all jobs in parallel
  #     # eats the bandwidth of all the nodes
  #     max-parallel: ${{ github.event_name != 'pull_request' && 6 || 10 }}
  #     matrix:
  #       include:


  #         # - build-type: 'cublas'
  #         #   cuda-major-version: "12"
  #         #   cuda-minor-version: "3"
  #         #   platforms: 'linux/amd64'
  #         #   tag-latest: 'false'
  #         #   tag-suffix: '-cublas-cuda12'
  #         #   ffmpeg: ''
  #         #   image-type: 'extras'
  #         #   runs-on: 'ubuntu-latest'
  #         #   base-image: "ubuntu:22.04"
  #         #   makeflags: "--jobs=3 --output-sync=target"



  core-image-build:
    uses: ./.github/workflows/image_build.yml
    with:
      tag-latest: ${{ matrix.tag-latest }}
      tag-suffix: ${{ matrix.tag-suffix }}
      ffmpeg: ${{ matrix.ffmpeg }}
      image-type: ${{ matrix.image-type }}
      build-type: ${{ matrix.build-type }}
      cuda-major-version: ${{ matrix.cuda-major-version }}
      cuda-minor-version: ${{ matrix.cuda-minor-version }}
      platforms: ${{ matrix.platforms }}
      runs-on: ${{ matrix.runs-on }}
      aio: ${{ matrix.aio }}
      base-image: ${{ matrix.base-image }}
      grpc-base-image: ${{ matrix.grpc-base-image }}
      makeflags: ${{ matrix.makeflags }}
      latest-image: ${{ matrix.latest-image }}
      latest-image-aio: ${{ matrix.latest-image-aio }}
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USER }}
      dockerPassword: ${{ secrets.DOCKER_TOKEN }}
      # quayUsername: ${{ secrets.LOCALAI_REGISTRY_USERNAME }}
      # quayPassword: ${{ secrets.LOCALAI_REGISTRY_PASSWORD }}
    strategy:
      max-parallel: ${{ github.event_name != 'pull_request' && 2 || 4 }}
      matrix:
        include:

          - build-type: 'cublas'
            cuda-major-version: "12"
            cuda-minor-version: "2"
            platforms: 'linux/amd64'
            tag-latest: 'false'
            tag-suffix: '-cublas-cuda12-2-core'
            ffmpeg: ''
            image-type: 'core'
            base-image: "ubuntu:22.04"
            runs-on: 'ubuntu-latest'
            makeflags: "--jobs=4 --output-sync=target"
